<a href="https://colab.research.google.com/github/DCarolinaLopezTulcan/Talento_Tech/blob/main/BibliotecasParaElManejoDeEstructuras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Verificar Instalacion de NumPy

In [ ]:
import numpy as np
print(np.__version__)

1.26.4


Creacion de ndarrays
1. A partir de listas:

In [ ]:
import numpy as np

#lista de numeros
numeros = [1,2,3,4,5]

#Creacion de un ndarray a partir de la lista
ndarray_numeros = np.array(numeros)

print(ndarray_numeros)




[1 2 3 4 5]


Creacion de ndarrays
2. Especificando dimensiones y valores:


In [ ]:
# Creacion de un ndarray de 2x3 con ceros
matriz_ceros = np.zeros((2,3))
print(matriz_ceros)

#Creacion de ndarray de 3x3 con unos
matriz_unos = np.ones((3,3))
print(matriz_unos)

#Creacion de un ndarray con valores especificos
matriz_personalizada = np.array([[1,2,3],[4,5,6]])
print(matriz_personalizada)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]]


3. Funciones de NumPy:

In [ ]:
import numpy as np
